### ISSUE TITLE
Package conflict when running --auto-deps - lazy-object-proxy

### ISSUE THREAD

**Issue by FurnitureFun** [Tremeschin/modular-music-visualizer#6]
Hello,

This looks like an amazing project, I'm hoping I can stream the output as well as rendering it to disk, however when I try and install it, I get the following error:

```
$ python example_basic.py --auto-deps
[ArgParser] --auto-deps True
[ArgParser] No given render target flag, assuming [gpu]
[Requirements.__init__] Python installation is 64 bits OK
[Requirements.__init__] Need to run Requirements, running from source
[Requirements.anything_to_do] Have requirements to install
[Requirements.anything_to_do] Upgrading PIP if needed
Collecting pip
  Using cached pip-20.3.3-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.4
    Uninstalling pip-20.2.4:
      Successfully uninstalled pip-20.2.4
Successfully installed pip-20.3.3
[Requirements.anything_to_do] Installing [wheel] package, less trouble installing other ones
WARNING: --use-feature=2020-resolver no longer has any effect, since it is now the default dependency resolver in pip. This will become an error in pip 21.0.
Requirement already satisfied: wheel in /.virtualenvs/mmv/lib/python3.8/site-packages (0.35.1)
Requirement already satisfied: wheel in /.virtualenvs/mmv/lib/python3.8/site-packages (0.35.1)
Collecting appdirs==1.4.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting astroid==2.4.2
  Downloading astroid-2.4.2-py3-none-any.whl (213 kB)
     |████████████████████████████████| 213 kB 4.8 MB/s 
INFO: pip is looking at multiple versions of appdirs to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r /modular-music-visualizer/mmv/modules/../mmv/requirements.txt (line 2) and lazy-object-proxy==1.5.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested lazy-object-proxy==1.5.1
    astroid 2.4.2 depends on lazy-object-proxy==1.4.*

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
Traceback (most recent call last):
  File "example_basic.py", line 37, in <module>
    requirements.install()
  File "/modular-music-visualizer/mmv/modules/end_user_utilities.py", line 111, in install
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-r', self.requirements_file])
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/.virtualenvs/mmv/bin/python', '-m', 'pip', 'install', '-r', '/modular-music-visualizer/mmv/modules/../mmv/requirements.txt']' returned non-zero exit status 1.
```
I'm running Python 3.8.6 on Arch Linux and using mkvirtualenv to create the virtual environment.

**Comment by Tremeschin** [comment]
I'll try fixing python packages deps tomorrow, after python 3.9 came stuff became weird, try going into requirements.txt and removing every ==version after the package names, or just install every package manually let pip get the latest package it can.

Rendering to video is default and current only way of actually running / using MMV, I'm spending last month quite some time learning shaders so hopefully I can make it not only ton lot faster but real time visualization or rendering, started writing stuff today in this regard :)

**Comment by Tremeschin** [comment]
Ah I think I know why this happened, I un blacklisted python 3.9 locally for me as I was moving to it and updated the requirements.txt with `pip freeze > requirements.txt` on my working venv so I basically let that one with a borked configuration for older versions and didn't even commit allowing python 3.9 from one assertion line of code, my bad.

It's easy to fix though don't worry I'll report back when I change it then test on clean virtual environments.

**Comment by Tremeschin** [comment]
Hey just refactored some code and split the main README into a folder called `mmv_skia`, using now `pip-chill` for getting the absolute minimum list of requirements and enforcing versions I installed here, I couldn't get it to run on Python 3.9 so please try using a Python 3.8 installation and venv (just replacing `python` with `python3.8` or `python38` should do it, and I have `python38` package installed on pacman here).

On a clean Python 3.8 venv (`python3.8 -m venv mmv-venv-38` I ran `python example_basic.py --auto-deps` and it installed everything, executed and is running properly.

Report back if you have any more issues and if it worked!! :)

Don't forget to `git pull` or `git pull --force` or delete and clone again the repo.

**Comment by FurnitureFun** [comment]
That's working perfectly, thank you!
